# Label incoming PRs automatically

components:
  - 'src/components/**/*'
  - 'src/data/contents/components/**/*'

blocks:
  - 'src/data/contents/blocks/**/*'

dashboards:
  - 'src/data/contents/dashboards/**/*'

documentation:
  - 'README.md'
  - 'CONTRIBUTING.md'
  - 'CODE_OF_CONDUCT.md'
  - 'SECURITY.md'
  - 'AI_POLICY.md'
  - 'CHANGELOG.md'
  - 'docs/**/*'

ci-cd:
  - '.github/**/*'
  - 'package.json'
  - 'bun.lockb'

website:
  - 'src/pages/**/*'
  - 'src/lib/**/*'
  - 'index.html'
