# Label incoming PRs automatically

components:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/components/**/*'
      - 'src/data/contents/components/**/*'

blocks:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/data/contents/blocks/**/*'

dashboards:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/data/contents/dashboards/**/*'

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'SECURITY.md'
      - 'AI_POLICY.md'
      - 'CHANGELOG.md'
      - 'docs/**/*'

ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'package.json'
      - 'bun.lockb'

website:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/pages/**/*'
      - 'src/lib/**/*'
      - 'index.html'
