import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();
const packageJsonPath = path.join(repoRoot, 'package.json');
const outputPath = path.join(repoRoot, 'src', 'data', 'ops.generated.ts');

type PackageJson = {
  name?: string;
  version?: string;
};

function git(args: string[]) {
  return execFileSync('git', args, {
    cwd: repoRoot,
    encoding: 'utf8',
  }).trim();
}

const packageJson = JSON.parse(
  fs.readFileSync(packageJsonPath, 'utf8'),
) as PackageJson;
const commitSha = git(['rev-parse', 'HEAD']);
const shortSha = git(['rev-parse', '--short', 'HEAD']);
const committedAt = git(['log', '-1', '--format=%cI']);
const branch = git(['rev-parse', '--abbrev-ref', 'HEAD']);
const generatedAt = new Date().toISOString();

const fileContents = `// This file is auto-generated by scripts/generate-ops-manifest.ts
// Do not edit by hand.

export const opsMetadata = {
  productName: ${JSON.stringify(packageJson.name ?? 'watermelon-platform')},
  publicProductName: 'Watermelon UI',
  packageVersion: ${JSON.stringify(packageJson.version ?? '0.0.0')},
  branch: ${JSON.stringify(branch)},
  commitSha: ${JSON.stringify(commitSha)},
  shortSha: ${JSON.stringify(shortSha)},
  committedAt: ${JSON.stringify(committedAt)},
  generatedAt: ${JSON.stringify(generatedAt)},
} as const;
`;

fs.writeFileSync(outputPath, fileContents);
console.log(`Ops manifest written to ${path.relative(repoRoot, outputPath)}`);
