import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import type { CatalogData, CatalogEntry, CatalogKind } from '../mcp/catalog';

const REPO_ROOT = path.resolve(import.meta.dirname, '..');
const CONTENTS_DIR = path.join(REPO_ROOT, 'src', 'data', 'contents');
const OUTPUT_PATH = path.join(REPO_ROOT, 'mcp', 'catalog.generated.ts');

const kindDirectories: Record<CatalogKind, string> = {
  'animated-components': 'registry',
  blocks: 'blocks',
  dashboards: 'dashboards',
  templates: 'templates',
  showcases: 'showcases',
};

function readMdxFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];

  const files: string[] = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      files.push(...readMdxFiles(fullPath));
      continue;
    }

    if (entry.name.endsWith('.mdx')) {
      files.push(fullPath);
    }
  }

  return files.sort((left, right) => left.localeCompare(right));
}

function buildEntries(kind: CatalogKind, directory: string): CatalogEntry[] {
  return readMdxFiles(path.join(CONTENTS_DIR, directory))
    .map((filePath) => {
      const frontmatter = matter.read(filePath).data as Record<string, unknown>;
      const slug = typeof frontmatter.slug === 'string' ? frontmatter.slug : '';
      const title = typeof frontmatter.title === 'string' ? frontmatter.title : '';

      if (!slug || !title) {
        return null;
      }

      return {
        kind,
        slug,
        title,
        description: typeof frontmatter.description === 'string' ? frontmatter.description : '',
        category: typeof frontmatter.category === 'string' ? frontmatter.category : undefined,
        image: typeof frontmatter.image === 'string' ? frontmatter.image : undefined,
        path: path.relative(REPO_ROOT, filePath).replaceAll(path.sep, '/'),
      } satisfies CatalogEntry;
    })
    .filter((entry): entry is CatalogEntry => entry !== null);
}

const catalog = Object.fromEntries(
  Object.entries(kindDirectories).map(([kind, directory]) => [
    kind,
    buildEntries(kind as CatalogKind, directory),
  ]),
) as CatalogData;

const banner = `// This file is auto-generated by scripts/generate-mcp-catalog.ts
// Do not edit by hand.

import type { CatalogData } from './catalog';

export const catalog: CatalogData = `;

const source = `${banner}${JSON.stringify(catalog, null, 2)} as CatalogData;\n`;

fs.writeFileSync(OUTPUT_PATH, source);
console.log(`Generated ${path.relative(REPO_ROOT, OUTPUT_PATH)} with ${Object.values(catalog).flat().length} entries.`);
